
language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: algo-messiahs
